= Narozeninový dort s čokoládou a malinami

Tento návod, slouží pro vytvoření narozeninového dortu, který bude ozdobou na každé oslavě.

== *Suroviny*

=== *Korpus*
* 200 g polohrubé mouky
* 200 g cukru prášek
* 60 g kakaa
* 2 vejce
* 100 ml oleje
* 200-230 ml mléka

=== *Náplň*
* 500 g mascrpone
* 1 smetana 36 %
* 50 cukru
* 1 ztužovač Smetafix
* mandlový extrakt

=== *Ozdobení*
* 250 g malin (pár dáme bokem na ozdobu))
* cukr podle chuti
* malinový džem nebo marmeláda
* 1 balení želé Dr. Oetker červené
* 1 smetana 36 %

=== *Postup*

. Mléko, vejce, olej našleháme, přidáme vše ostatní a mícháme, až se vše krásně spojí.
. Pečeme v dortové formě s vymaštěným a vysypaným pečícím papírem na 170 ° přibližně 15-20 min.
Je potřeba udělat test špejlí.
+
  Upečený a vychlazený korpus prořízneme na dva pláty.

. Mezitím rozvaříme maliny s cukrem (množství je individuální) a přepasírujeme přes husté síto. Část odebereme na pozdější vaření želatiny.

. Mascarpone pořádně rozmixujeme na jemno a dáme bokem.

. Smetanu a ztužovač smícháme s cukrem a vyšleháme na tuhou šlehačku. Postupně po malých částech přidáváme mascarpone a promícháme.

. Hotový krém rozdělíme na dvě poloviny, do jedné přidáme mandlový extrakt a druhou polovinu smícháme s malinovým rozvarem.

. Uvaříme želé podle návodu na zadní straně (použijeme odebraný malinový rozvar a doplníme vodou do požadovaného množství).

. Do dortové formy dáme první plát, který potřeme po celé ploše malinovou marmeládou, na to uvařené želé a vše necháme ztuhnout (stačí ½ hodiny).
+
  Na ztuhlou želatinu navršíme bílý mandlový krém, na to druhý plát korpusu a opět malinový krém.
  Urovnáme a dáme ztuhnout do lednice. Nejlépe přes noc.

. Hotový moučník ozdobíme ušlehanou smetanou a ovocem.


=== Zdroj

* link:https://www.toprecepty.cz/recept/58260-cokoladovo-malinovy-sen/[TopRecepty - cokoladovo-malinovy sen]
